### ISSUE TITLE
Front-End has some issues with Google OAuth sign in/login

### ISSUE THREAD

**Issue by rohanajm7** [jashgopani/application-tracking-system#7]
When I try to login using google oauth from the frontend in our app, I am facing the following error - 
![image](https://github.com/jashgopani/application-tracking-system/assets/66876265/05ad6341-bed2-443b-8543-fbcaf91b0c25)

Whereas, I tried the URL directly and it is actually working.

**Comment by jashgopani** [comment]
You're seeing this issue probably because if you're on a mac and you've configured the redirect URI in terms of localhost instead of 127.0.0.1 or vice versa for windows. This issue would be solved by the dockerization enhancement that you can see in the discussions channel.
We will close this issue once that feature is released.

**Comment by hemil26** [comment]
This issue has now resolved after dockerizing the application
