### ISSUE TITLE
Authentication not working 

### ISSUE THREAD

**Issue by hemil26** [jashgopani/application-tracking-system#8]
There is an issue in signing in and creating a new user, it shows a message which says 
"Error while signing up!" 
This error is coming on MacOS

**Comment by jashgopani** [comment]
Hi @hemil26,
This issue might be due to one of the following reasons
1. Incorrect MongoDB setup
2. The usage of "localhost" in URL strings in frontend code / google console redirect URI (as mac od does not resolve localhost, use 127.0.0.1 instead)

To resolve this issue we are dockerizing the application. Please follow the updates channel for the same.
